[package]
name = "rust-company-track"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.29.0", features = ["bundled"] }
cuid = "1.3.2"
colored = "2.0.4"
dialoguer = "0.11.0"
